name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "next"
env:
  PRETTIER_BRANCH: ${{ github.event.inputs.branch || 'next' }}
  SKIP_PRODUCTION_INSTALL: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: prettier/prettier
          ref: ${{ env.PRETTIER_BRANCH }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build --clean --no-minify

      - name: Update c8 config
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('node:fs')
            const packageJson = JSON.parse(fs.readFileSync('./package.json'))
            packageJson.c8.include = ['dist/**'];
            fs.writeFileSync('./package.json', JSON.stringify(packageJson, undefined, 2))

      - name: Run Tests
        run: yarn c8 yarn test:dist

      - name: Upload Coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

